# Generated by make formula. Copy to jakemanger/homebrew-tap after release.
class Lsa < Formula
  desc "ls for agent sessions"
  homepage "https://github.com/jakemanger/lsa"
  url "https://github.com/jakemanger/lsa/releases/download/v0.1.0/lsa"
  version "0.1.0"
  sha256 "66e96e469b181ac4533bb7e4718c485c627639b821adc83d8ba4510d60678e45"
  license "MIT"

  depends_on "jq"
  depends_on "sqlite"

  def install
    bin.install "lsa"
  end

  def caveats
    <<~'EOS'
      Oh My Zsh? Replace its default lsa='ls -lah' alias with the lsa command:
      printf '\nunalias lsa 2>/dev/null\n' >> ~/.zshrc && source ~/.zshrc
    EOS
  end

  test do
    assert_equal "lsa 0.1.0", shell_output("#{bin}/lsa --version").strip
    assert_match "ls for agent sessions", shell_output("#{bin}/lsa --help")
  end
end
