# Generated by make formula. Copy to jakemanger/homebrew-tap after release.
class Lsa < Formula
  desc "ls for agent sessions"
  homepage "https://github.com/jakemanger/lsa"
  url "https://github.com/jakemanger/lsa/releases/download/v0.1.0/lsa"
  version "0.1.0"
  sha256 "191f5773427e3e34d94cf5fc42abf7bdbd8624c0d649477848a45b275bf2e204"
  license "MIT"

  depends_on "jq"
  depends_on "sqlite"

  def install
    bin.install "lsa"
  end

  def caveats
    <<~EOS
      Oh My Zsh: run unalias lsa in your current terminal.
      Add unalias lsa 2>/dev/null to the end of ~/.zshrc for new terminals.
    EOS
  end

  test do
    assert_equal "lsa 0.1.0", shell_output("#{bin}/lsa --version").strip
    assert_match "ls for agent sessions", shell_output("#{bin}/lsa --help")
  end
end
