# Generated by make formula. Copy to jakemanger/homebrew-tap after release.
class Lsa < Formula
  desc "ls for agent sessions"
  homepage "https://github.com/jakemanger/lsa"
  url "https://github.com/jakemanger/lsa/releases/download/v0.1.0/lsa"
  version "0.1.0"
  sha256 "048448bbc13c5078a8929bcf27434bda39be1205fa156b1590d022108d34ea75"
  license "MIT"

  depends_on "jq"
  depends_on "sqlite"

  def install
    bin.install "lsa"
  end

  def caveats
    <<~'EOS'
      Oh My Zsh? Replace its default lsa='ls -lah' alias with the lsa command:
      printf '\nunalias lsa 2>/dev/null\n' >> ~/.zshrc && source ~/.zshrc
    EOS
  end

  test do
    assert_equal "lsa 0.1.0", shell_output("#{bin}/lsa --version").strip
    assert_match "ls for agent sessions", shell_output("#{bin}/lsa --help")
  end
end
