#!/usr/bin/env bash
# Generate the tap formula from the exact standalone file released as "lsa".
set -eu
cd "$(dirname "$0")/.."
version=$(sed -n 's/^VERSION="\(.*\)"/\1/p' lsa)
sha=$(shasum -a 256 lsa | cut -d' ' -f1)
cat <<EOF
# Generated by make formula. Copy to jakemanger/homebrew-tap after release.
class Lsa < Formula
  desc "ls for agent sessions"
  homepage "https://github.com/jakemanger/lsa"
  url "https://github.com/jakemanger/lsa/releases/download/v$version/lsa"
  version "$version"
  sha256 "$sha"
  license "MIT"

  depends_on "jq"
  depends_on "sqlite"

  def install
    bin.install "lsa"
  end

  def caveats
    <<~'EOS'
      Oh My Zsh? Replace its default lsa='ls -lah' alias with the lsa command:
      printf '\nunalias lsa 2>/dev/null\n' >> ~/.zshrc && source ~/.zshrc
    EOS
  end

  test do
    assert_equal "lsa $version", shell_output("#{bin}/lsa --version").strip
    assert_match "ls for agent sessions", shell_output("#{bin}/lsa --help")
  end
end
EOF
